### PR TITLE
Avoid return undefined

### PR DESCRIPTION
**Pull request by jobo322**
return undefined requires checking types, for example `number | undefined`, I just did change the method that I currently need but it could be generalized for all the other methods if you agree.

### CODE REVIEW

**Comment by targos** [comment]
Why does the code use "manual matrices" (2d arrays) instead of ml-matrix?

**Comment by lpatiny** [comment]
> Why does the code use "manual matrices" (2d arrays) instead of ml-matrix?

Those are some basic calculations used in spectra analysis that may involve large matrices and I didn't want to duplicate the data (if I understood well ml-matrix will always clone the data as Float64Array internally). For Julien we should have 500 spectra of 128k points.

**Comment by targos** [comment]
I'm not saying that the method should convert the data to a matrix here, but that a matrix should be accepted/used by the calling code

**Comment by lpatiny** [comment]
Sorry I didn't understand this. Yes sure good idea ! I will add an issue about this.

**Pull request merged**
