### PR TITLE
feat: add sorted option to xFindClosestIndex function

### PR DESCRIPTION
**Pull request by josoriom**

### CODE REVIEW

**Comment by lpatiny** [comment]
It seems there is a migration to TS in this PR as well and this migration was already assign to @wadjih-bencheikh18 https://github.com/mljs/spectra-processing/issues/92

@josoriom if you are doing migration you should check if there is an issue for this topic. If not create it and assign yourself.

@wadjih-bencheikh18 what is the current status of your work on this migration ?

**Comment by wadjih-bencheikh18** [comment]
I finished the migration there's just two problems
Ml-gsd typescript version didn't release yet ( comment added)

**Comment by wadjih-bencheikh18** [comment]
https://github.com/mljs/spectra-processing/issues/92#issuecomment-954644845
Also there is this issus

**Comment by lpatiny** [comment]
> I finished the migration there's just two problems
> 
> -[mljs/global-spectral-deconvolution#59 (comment)](https://github.com/mljs/global-spectral-deconvolution/issues/59#issuecomment-955041138) Ml-gsd typescript version didn't release yet ( comment added)
> 
> -[#92 (comment)](https://github.com/mljs/spectra-processing/issues/92#issuecomment-954644845) Also there is this issus

Ok please open the PR for the TS migration.

**Comment by wadjih-bencheikh18** [comment]
Ok, but do you want me to open a PR with those two problems?

**Comment by lpatiny** [comment]
> Ok, but do you want me to open a PR with those two problems?

Yes it is always easier to solve seeing the code.

You can also in the future open a PR as draft to know you are working on the project. And if you mention in a commit a 'close #xx' it would probably move directly the ticket in 'processing' in https://github.com/orgs/mljs/projects/3 (I did it manually this time)

**Comment by wadjih-bencheikh18** [comment]
> > Ok, but do you want me to open a PR with those two problems?
> 
> Yes it is always easier to solve seeing the code.
> 
> You can also in the future open a PR as draft to know you are working on the project. And if you mention in a commit a 'close #xx' it would probably move directly the ticket in 'processing' in https://github.com/orgs/mljs/projects/3 (I did it manually this time)

PR Opened

**Pull request merged**
